name: Checkout for Release Plan
description: 'Checkout for Release Plan; checkout must run first'

inputs:
  ref:
    description: 'Primary branch'
    required: true
    default: 'main'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      # We need to download lots of history so that
      # github-changelog can discover what's changed since the last release
      with:
        fetch-depth: 0
        ref: ${{ inputs.ref }}
