name: Check if latest commit is a release
description: 'Checks if the latest commit triggers a release via release-plan'

outputs:
  is-release:
    description: "String 'release' when the latest commit modified the .release-plan.json file to trigger a release"
    value: ${{ steps.check-release.outputs.is_release }}

inputs:
  ref:
    description: 'Primary branch'
    required: true
    default: 'main'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
        ref: ${{ inputs.ref }}
    - id: check-release
      run: if git diff --name-only HEAD HEAD~1 | grep -w -q ".release-plan.json"; then echo "is_release=release"; fi >> $GITHUB_OUTPUT
      shell: bash
