name: Plan Release
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
  pull_request_target: # This workflow has permissions on the repo, do NOT run code from PRs in this workflow. See https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
    types:
      - labeled
      - unlabeled

concurrency:
  group: plan-release # only the latest one of these should ever be running
  cancel-in-progress: true

jobs:
  should-generate-release-plan:
    name: "Should generate release plan?"
    runs-on: ubuntu-latest
    outputs:
      should-generate: ${{ steps.should-generate.outputs.should-generate }}
    steps:
      - uses: kategengler/actions/release-plan/check-if-release@v0.0.11
        with:
          ref: 'main'
          event-name: ${{ github.event_name }}
          github-event: ${{ github.event }}
        id: should-generate

  create-prepare-release-pr:
    name: Create Prepare Release PR
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: should-generate-release-plan
    permissions:
      contents: write
      issues: read
      pull-requests: write
    # only run on push event or workflow dispatch if plan wasn't updated (don't create a release plan when we're releasing)
    # only run on labeled event if the PR has already been merged
    if: needs.should-generate-release-plan.outputs.should-generate == 'true' 
    steps:
      - uses: kategengler/actions/release-plan/checkout@v0.0.11
        with:
          ref: 'main'
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      # Optionally install deps here
      - uses: kategengler/actions/release-plan/prepare@v0.0.11
        name: "Run release-plan prepare"
        env:
          GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}
        id: explanation

      - uses: peter-evans/create-pull-request@v7
        name: "Create Prepare Release PR"
        with:
          commit-message: "Prepare Release ${{ steps.explanation.outputs.new-version}} using 'release-plan'"
          labels: "internal"
          branch: release-preview
          title: Prepare Release ${{ steps.explanation.outputs.new-version }}
          body: |
            This PR is a preview of the release that [release-plan](https://github.com/embroider-build/release-plan) has prepared. To release you should just merge this PR 👍

            -----------------------------------------

            ${{ steps.explanation.outputs.text }}
